version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  namenode:
    image: apache/hadoop:3.3.1
    container_name: namenode
    ports:
      - "9870:9870" # HDFS Web UI
      - "9000:9000" # HDFS RPC
    environment:
      - HADOOP_NODE_TYPE=namenode
      - CLUSTER_NAME=hadoop_cluster

  datanode:
    image: apache/hadoop:3.3.1
    container_name: datanode
    environment:
      - HADOOP_NODE_TYPE=datanode
      - CLUSTER_NAME=hadoop_cluster
    depends_on:
      - namenode

  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    ports:
      - "7077:7077" # Spark master port
      - "8080:8080" # Spark UI
    environment:
      - SPARK_MODE=master
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop

  spark-worker:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_SECRET_KEY=your_secret_key
    depends_on:
      - clickhouse-server
    entrypoint: >
      /bin/bash -c "
      superset db upgrade &&
      superset init &&
      superset run -p 8088 -h 0.0.0.0"
    volumes:
      - superset_home:/app/superset_home

volumes:
  clickhouse_data:
  clickhouse_logs:
  superset_home:
