services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mynetwork

  kafka-server:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  hadoop-namenode:
    image: apache/hadoop:3.3.5
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop-namenode:/opt/hadoop/data/nameNode
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
    ports:
      - "9870:9870"
      - "9000:9000"
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    networks:
      - mynetwork

  hadoop-datanode-1:
    image: apache/hadoop:3.3.5
    container_name: hadoop-datanode-1
    hostname: hadoop-datanode-1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop-datanode-1:/opt/hadoop/data/dataNode
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    ports:
      - "9864:9864"
    depends_on:
      - hadoop-namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      - mynetwork

  hadoop-datanode-2:
    image: apache/hadoop:3.3.5
    container_name: hadoop-datanode-2
    hostname: hadoop-datanode-2
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop-datanode-2:/opt/hadoop/data/dataNode
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    ports:
      - "9865:9864"
    depends_on:
      - hadoop-namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      - mynetwork

  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey123
      - DATABASE_URL=postgresql+psycopg2://superset:supersetpassword@postgres:5432/superset
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./superset-home:/app/superset_home
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    command: >
      bash -c "
      pip install clickhouse-connect psycopg2-binary pymongo && superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname Admin --email admin@example.com --password admin &&
      superset load_examples &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    container_name: superset_postgres
    restart: always
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: supersetpassword
      POSTGRES_DB: superset
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: superset-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge